### ISSUE TITLE
Example data.json not valid

### ISSUE THREAD

**Issue by moretaste** [mohitsinghs/gulp-nunjucks-md#1]
There are some unwanted trailing commas in the example data.json

The correct markup should be 
```
{
  "site": {
    "title": "Example Site",
    "url": "http://example.com"
  },
    "boxes" : [
    {
      "title": "red"
    },
    {
      "title": "green"
    },
    {
      "title": "blue"
    }
  ]
}
```

**Comment by mohitsinghs** [comment]
Absolutely, Thanks for catching that. Actually this was already fixed in [tests](https://github.com/mohitsinghs/gulp-nunjucks-md/blob/master/test/fixtures/data.json) but I forgot to update the example. Fixed now, so can we close this ?

**Comment by mohitsinghs** [comment]
Absolutely, Thanks for catching that. Actually this was already fixed in [tests](https://github.com/mohitsinghs/gulp-nunjucks-md/blob/master/test/fixtures/data.json) but I forgot to update the example. Fixed now, so it closing this.
