### ISSUE TITLE
Markdown render issue when no frontmatter

### ISSUE THREAD

**Issue by nicolas-cusan** [mohitsinghs/gulp-nunjucks-md#4]
Hi @mohitsinghs,

thank you for the update.

Currently I have the issue that files that do not contain frontmatter (where layout is set via data), do not get interpreted as markdown. I guess the problem is here https://github.com/mohitsinghs/gulp-nunjucks-md/blob/master/index.js#L72 `md` is only called if front matter is present.

Thank you for having a look, if yo prefer I can als make a pull request.

**Comment by mohitsinghs** [comment]
I actually initially made changes for this but just missed during code cleanup. Thanks for pointing out. v1.3.1 is on the way.

**Comment by mohitsinghs** [comment]
v1.3.1 is out. 🎉 This should be fixed now.

**Comment by nicolas-cusan** [comment]
@mohitsinghs works, thank you!
